steps:
  # Build using your Dockerfile in the current directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/apex-fusion-mainnet-001/apex-mainnet/cardano-node:9.2.1'
      - '.'

  # Push the newly built image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/apex-fusion-mainnet-001/apex-mainnet/cardano-node:9.2.1'
images:
  - 'us-central1-docker.pkg.dev/apex-fusion-mainnet-001/apex-mainnet/cardano-node:9.2.1'
  