version: "1"
name: prime-mainnet-9.2.1

services:
  # ===========
  # prime relay
  # ===========
  #
  # standalone
  prime-relay:
    image: ghcr.io/intersectmbo/cardano-node:9.2.1
    environment:
      - CARDANO_BLOCK_PRODUCER=false
      - CARDANO_CONFIG=/config/configuration.yaml
      - CARDANO_TOPOLOGY=/config/topology.json
      - CARDANO_DATABASE_PATH=/data/db
      - CARDANO_SOCKET_PATH=/ipc/node.socket
      - CARDANO_LOG_DIR=/data/node.log
      - CARDANO_BIND_ADDR=0.0.0.0
      - CARDANO_PORT=3001
    command:
      - run
    volumes:
      - ./config/node:/config
      - node-db:/data/db
      # use either docker volume (see volumes below) or local host folder if interracting from host over ipc
      # change here affects - db-sync, ogmios
      # - node-ipc:/ipc
      - ./node-ipc:/ipc
    restart: on-failure
    healthcheck:
      # Ping the EKG port to see if it responds.
      # Assuming if EKG isn't up then the rest of cardano-node isn't either.
      test: ["CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  # required for: prime-relay
  # node-ipc:
  node-db:
